#!/bin/sh

# 0.1 Initial Release
# Created PostProcessing Configuration File
# Added Variables for TV/Movies Folder, download paths, local and remote Sync Paths, remote Sync age, remotesyncfiles, searchVars for season remote sync and excludelist, kodiHost, use exlude list
# Created postprocessing.sh
# Added include config file
# Added checks for local Mount Paths
# Added mount functions for Remote Paths
# Added unmount functions for Remote Paths
# Added collect files functions
