#!/bin/sh
#
# @license http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author David Hönel <davidh1990@gmx.de>
# @copyright Copyright (c) 2015 David Hönel
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

########################################
# PostProcessing Scripts Configuration #
########################################

### Post Processing Settings ###

## General Post Processing Settings ##
# Filebot Cleaner # 
enableFilebotCleaner=false # (default: false, allowed: true, false) Cleans up useless junk in your download Folder thats left after postprocessing.

## TV Show Settings ##
# Download Path TV Shows (Where are your TV Shows stored after downloading?)
downloadPathTVNative="/opt/SAB1/Downloads/complete/tv" # Your native Language (Full Path!)
downloadPathTVSecond="/opt/SAB2/Downloads/complete/tv" # Second language, if used MUST be separate Folder from your native Language (Full Path!)
# TV Shows Folder
destinationPathTVNative="Deutsch" # Your native Language (Only fill in the Language, leave empty if you don't want to use it)
destinationPathTVSecond="English" # Your second Language, can be seperate Folder from your native Language if you wish, leave empty if you don't need it)
## Filebot Syntax Settings ## Those Settings are used to properly rename the files
# TV Show Folder
filebotTVFolder="{n.replaceAll(/[!?.]+\$/).replaceAll(/[\`´‘’ʻ]/, \"'\").replace(':',' -')}"
# TV Show Season
filebotTVSeasonNative="Staffel {s} DE + EN {vf}"
filebotTVSeasonSecond="Staffel {s} EN {vf}"
# TV Show File
filebotTVFile="{t.replaceAll(/[!?.]+\$/).replaceAll(/[\`´‘’ʻ]/, \"'\").replace(':',' -')}"
# TV Show Database
filebotTVDB="--db thetvdb"
# TV Show language # Which Language should be used to rename the TV Show Episode?
filebotTVLanguage="--lang en"
# TV Show - Go recursive through the Download Folder. Empty the variable if you don't want to use it.
filebotTVRecursive="-r"
# TV Show - Use non-strict matching
filebotTVNonstrict=""
# TV Show - Override Setting
filebotTVOverride="--override auto"

## Movies Settings ##
# Download Path (Where are your Movies stored after downloading?)
downloadPathMoviesNative="" # Your native Language (Full Path!)
downloadPathMoviesSecond="" # Second language, if used MUST be separate Folder from your native Language (Full Path!)
# Movies Folder
destinationPathMoviesNative="" # Your native Language (Only fill in the Language, leave empty if you don't want to use it) (Full Path!)
destinationPathMoviesSecond="" # Your second Language, can be seperate Folder from your native Language if you wish, leave empty if you don't need it) (Full Path!)
## Filebot Syntax Settings ## Those Settings are used to properly rename the files
# Movie Folder 
filebotMoviesFolder="{n.replaceAll(/[!?.]+\$/).replaceAll(/[\`´‘’ʻ]/, \"'\").replace(':',' -')} ({y}) {vf}"
# Movie File
filebotMoviesFile="{n.replaceAll(/[!?.]+\$/).replaceAll(/[\`´‘’ʻ]/, \"'\").replace(':',' -')} ({y}) {vf}{' CD'+pi}"
# Movies Database
filebotMoviesDB="--db themoviedb"
# Movies Language # Which Language should be used to rename the Movie? 
filebotMoviesLanguage="--lang de"
# Movies - Go recursive through the Download Folder. Empty the variable if you don't want to use it
filebotMoviesRecursive="-r"
# Movies - Filebot non-strict matching Setting
filebotMoviesNonstrict="-non-strict"
# Movies - Filebot Override Setting
filebotMoviesOverride="--override auto"

## Stereo Filter (Movies only!) ##
# Enable Filter for Stereo Audio
useStereoFilter="false" # (Default: false, allowed: true, clean)
stereoFilterMatchedFiles="/tmp/stereofiltermatchedfiles" # Do NOT change.
stereoFilterTempPath="/opt/tmp/" # Do NOT change.
# Where do you want to move the Movies with Stereo Audio Tracks to?
stereoFilterDestinationPathNative="" # Your Native Language, MUST be set if useStereoFilter is set to true. (Full Path!)
stereoFilterDestinationPathSecond="" # Your Second Language, MUST be set (but can be the same as PathNative). (Full Path!)

## Kodi Library Update ##
# Enable Kodi Library Update
useKodiLibraryUpdate="false" # (Default: false, allowed: true, clean)
# Kodi Library Update Host (On which Host is Kodi running that can update the Library?)
kodiHost=""
# Wait time between triggering a Clean and an Update of the Kodi Library
kodiCleanWaitTime="15" # (Default: 15, allowed: 1-X, measured in seconds)

### Remote Sync Settings ###

## Remote Sync General Settings ##
# Enable Remote Sync within Post Processing
enableRemoteSyncInPostProcessingTV="false" # (Default: false, allowed: true, false)
enableRemoteSyncInPostProcessingMovies="false" # (Default: false, allowed: true, false)

## Remote Sync TV Settings ##
localSyncPathTV="/mnt/synctv" # Do NOT change me!
# Remote Path for Sync in the Remote Filesystem
remoteSyncPathTV="192.168.178.66:/export/Serien/Serien"
# Set Timeframe for Remote Path Sync TV
remoteSyncAgeTV="-14" # (Default: -14 Days)
# Use exclude List for TV Shows
useExcludeListTV="false" # (Default: false, allowed: true, false)

## Remote Sync Movie Settings ##
localSyncPathMovies="/mnt/syncmovies" # Do NOT change me!
# Remote Path for Movies in the Remote Filesystem
remoteSyncPathMovies=""
# Set Timeframe for Remote Path Sync Movies
remoteSyncAgeMovies="0" # (Default: 0 = Disabled;)
# Use exclude List for Movies 
useExcludeListMovies="false" # (Default: false, allowed: true, false)

# DO NOT CHANGE ANY VARIABLES HERE! #
filesForRemoteSync="/tmp/remotesyncfiles"
excludeListTV="/etc/default/postprocessingexcludelistTV"
excludeListMovies="/etc/default/postprocessingexcludelistMovies"